### ISSUE TITLE
install des not work on latest version of Rasbian Jessie light

### ISSUE THREAD

**Issue by naylogj** [pivpn/pivpn#200]
# PiVPN Issue Template

## Console output of `curl install.pivpn.io | bash`
```
curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    258      0 --:--:-- --:--:-- --:--:--   258
100 43750  100 43750    0     0  52915      0 --:--:-- --:--:-- --:--:-- 52915
:::
::: sudo will be used for the install.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site.py", line 563, in <module>
    main()
  File "/usr/lib/python2.7/site.py", line 545, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python2.7/site.py", line 272, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python2.7/site.py", line 247, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python2.7/site.py", line 237, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python2.7/sysconfig.py", line 582, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python2.7/sysconfig.py", line 509, in get_config_vars
    import re
  File "/usr/lib/python2.7/re.py", line 105, in <module>
    import sre_compile
  File "/usr/lib/python2.7/sre_compile.py", line 15, in <module>
    import sre_parse
ValueError: bad marshal data (string ref out of range)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site.py", line 563, in <module>
    main()
  File "/usr/lib/python2.7/site.py", line 545, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python2.7/site.py", line 272, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python2.7/site.py", line 247, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python2.7/site.py", line 237, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python2.7/sysconfig.py", line 582, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python2.7/sysconfig.py", line 509, in get_config_vars
    import re
  File "/usr/lib/python2.7/re.py", line 105, in <module>
    import sre_compile
  File "/usr/lib/python2.7/sre_compile.py", line 15, in <module>
    import sre_parse
ValueError: bad marshal data (string ref out of range)


```

## Console output of `pivpn add` or `pivpn add nopass`
```

```

## Console output of `pivpn debug`
```

```

## Issue
hi - trying to install pivpn on the latest version of Rasbian Jessie lite [11.01.17] and get the above errors.  It is a clean build, downloaded today, followed by sudo apt-get update && sudo apt-get upgrade ; which worked successfully, rebooted, ran the curl command to install pivpn and got the above errors.
Help appreciated please.

**Comment by 0-kaladin** [comment]
I don't think its the install but rather some package that is messed up.  if you run apt-get update and upgrade again does it go by cleanly?
what about trying:
sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 10
sudo update-alternatives --set python /usr/bin/python2.7

and
sudo dpkg --configure -a

see if any of those commands give errors.

we don't use python so not sure why python2.7 is showing up at all.  hence my guesses above.

**Comment by naylogj** [comment]
hi 0-kaladin, thanks for your help.  You were right - nothing to do with pivpn.  I tried your suggestions but this did not fix the issue.  There were other issues - so looks like a corrupt OS install.  So I re-installed the Jessie OS on the SD card, did an update and upgrade and now have pivpn installed.  Many thanks.
