### ISSUE TITLE
Unable to install on Raspberry Pi 1 B+

### ISSUE THREAD

**Issue by mangusbrother** [pivpn/pivpn#663]
Output given:
```
::: sudo will be used for the install.
Traceback (most recent call last):
  File "/usr/bin/lsb_release", line 95, in <module>
    main()
  File "/usr/bin/lsb_release", line 59, in main
    distinfo = lsb_release.get_distro_information()
AttributeError: module 'lsb_release' has no attribute 'get_distro_information'
```

Some more details:
```
pi@raspberrypi:~ $ sudo iptables -t nat -S
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
pi@raspberrypi:~ $ sudo iptables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
pi@raspberrypi:~ $ sudo netstat -uanp | grep openvpn
pi@raspberrypi:~ $
```

only other thing on this pi installed is pi-hole (which is the dns server for the network as well) however the fallback google dns is working fine.

**Comment by devZer0** [comment]
what's your distro ?
